---
    apiVersion: v1
    kind: Service
    metadata:
      name: mysql
      labels:
        app: wordpress
    spec:
      ports:
        - port: 3306
      selector:
        app: wordpress
        tier: mysql