---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: my-wordpress
  labels:
    app: wordpress
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql
    spec:
      hostname: db
      subdomain: mysql
      containers:
        - image: mysql:5.7
          name: mysql
          env:
            - name: MYSQL_DATABASE
              value: wordpress_db
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                    name: mysql
                    key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                    name: mysql
                    key: password 
            - name: MYSQL_RANDOM_ROOT_PASSWORD
              value: '1'
          ports:
            - containerPort: 3306
              name: mysql
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 3
            periodSeconds: 3              
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 10
            periodSeconds: 5 
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim             